### ISSUE TITLE
error: Could not connect to the server 127.0.0.1:8331 (error code 1 - "EOF reached") on openbsd

### ISSUE THREAD

**Issue by ndalliard** [Kixunil/btc-rpc-proxy#17]
1. running `cargo run --release -- --conf btc_rpc_proxy.toml` with:

```toml
bitcoind_user = "nathanael"
bitcoind_password = "[redacted]"
bind_address = "127.0.0.1"

[user.test]
password = "test"
allowed_calls = [
        "getmininginfo"
]
````

2. running `bitcoin-cli -rpcuser=test -rpcpassword=test -rpcport=8331 getmininginfo`:

````shell
error: Could not connect to the server 127.0.0.1:8331 (error code 1 - "EOF reached")

Make sure the bitcoind server is running and that you are connecting to the correct RPC port.
````

the proxy is running cause `netstat -na -f inet | grep 8331` gives me:
````
tcp          0      0  127.0.0.1.8331         *.*                    LISTEN
````

of course when i run `bitcoin-cli -rpcuser=nathanael -rpcpassword=[redacted] getmininginfo` it works (using the values inserted in the config file of btc-rpcy-proxy seen above)

has anyone an idea what i am doing wrong? something to do with openbsd?
